### ISSUE TITLE
planning: ebtc ui

### ISSUE THREAD

**Issue by okjintao** [ebtc-protocol/ebtc#62]
# Tasks

Tasks will be listed in the order they should be completed. As tasks are finished their respective check boxes should be ticked, and timelines updated accordingly. Tasks within batches may be completed parallel to others.

Tasks such as the SDK are required for UI development and thus captured in this planning document. The top level issue will contain tracking information internally for all tasks related to SDK development as to allow for UI development timeline clarity.

Batch 0
- [x] https://github.com/Badger-Finance/ebtc/issues/59 - Est: 2-3 days
- [x] https://github.com/Badger-Finance/ebtc/issues/60 - Est: 5-7 days
- [x] https://github.com/Badger-Finance/ebtc/issues/64 - Est: 2-3 weeks

Batch 1
- [x] https://github.com/Badger-Finance/ebtc/issues/61 - Est: 5-7 days
- [x] https://github.com/Badger-Finance/ebtc/issues/63 - Est: 2-3 days

Batch 2

- [x] #74 - Est: 1-2 weeks
- [x] #75 - Est: 1 week
- [ ] #76 - Est: 1-2 weeks
- [x] #77 - Est: 2-3 weeks
- [x] #78 - Est: 3-4 weeks

Batch 3

- [x] #79
- [x] #80
- [x] #81
